# Generated by Django 4.1.6 on 2023-03-10 10:35
import json
import os
from django.conf import settings
from django.db import migrations


def get_initial_data(file_name):
    data_file = open(os.path.join(
        settings.BASE_DIR, 'db_initial_data/', file_name)
    )
    initial_data = json.load(data_file)
    data_file.close()
    return initial_data


def add_tags(apps, schema_editor):
    initial_data = get_initial_data('tags.json')
    Tag = apps.get_model('recipes', 'Tag')
    for tag in initial_data:
        new_tag = Tag(**tag)
        new_tag.save()


def remove_tags(apps, schema_editor):
    initial_data = get_initial_data('tags.json')
    Tag = apps.get_model('recipes', 'Tag')
    for tag in initial_data:
        Tag.objects.get(**tag).delete()


def add_ingredients(apps, schema_editor):
    initial_data = get_initial_data('ingredients.json')
    Ingredient = apps.get_model('recipes', 'Ingredient')
    for ingredient in initial_data:
        new_ingredient = Ingredient(**ingredient)
        new_ingredient.save()


def remove_ingredients(apps, schema_editor):
    initial_data = get_initial_data('ingredients.json')
    Ingredient = apps.get_model('recipes', 'Ingredient')
    for ingredient in initial_data:
        Ingredient.objects.get(**ingredient).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            remove_tags
        ),
        migrations.RunPython(
            add_ingredients,
            remove_ingredients
        )

    ]
